[32m2024-11-26 13:00:29 +0100[0m - dagster - [34mDEBUG[0m - tech_sentiment_job - 7e768a07-bf2e-41cb-840c-19e8f88643bb - 274018 - LOGS_CAPTURED - Started capturing logs in process (pid: 274018).
[32m2024-11-26 13:00:29 +0100[0m - dagster - [34mDEBUG[0m - tech_sentiment_job - 7e768a07-bf2e-41cb-840c-19e8f88643bb - 274018 - extract_all_data - STEP_START - Started execution of step "extract_all_data".
[32m2024-11-26 13:00:30 +0100[0m - dagster - [34mERROR[0m - [31mtech_sentiment_job - 7e768a07-bf2e-41cb-840c-19e8f88643bb - 274018 - extract_all_data - STEP_FAILURE - Execution of step "extract_all_data" failed.

dagster._core.errors.DagsterInvariantViolationError: Cannot access partition_key for a non-partitioned run

Stack Trace:
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_plan.py", line 245, in dagster_event_sequence_for_step
    for step_event in check.generator(step_events):
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 499, in core_dagster_event_sequence_for_step
    for user_event in _step_output_error_checked_user_event_sequence(
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 183, in _step_output_error_checked_user_event_sequence
    for user_event in user_event_sequence:
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/execute_step.py", line 87, in _process_asset_results_to_events
    for user_event in user_event_sequence:
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute.py", line 197, in execute_core_compute
    for step_output in _yield_compute_results(step_context, inputs, compute_fn, compute_context):
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute.py", line 166, in _yield_compute_results
    for event in iterate_with_context(
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_utils/__init__.py", line 482, in iterate_with_context
    next_output = next(iterator)
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute_generator.py", line 140, in _coerce_op_compute_fn_to_iterator
    result = invoke_compute_fn(
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/plan/compute_generator.py", line 128, in invoke_compute_fn
    return fn(context, **args_to_pass) if context_arg_provided else fn(**args_to_pass)
  File "/home/urban/Projekty/dagster2/my-dagster-project/quickstart_etl/assets/db_pipeline.py", line 16, in extract_all_data
    partition_key = context.partition_key  # Pobierz klucz partycji
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/context/asset_execution_context.py", line 378, in partition_key
    return self.op_execution_context.partition_key
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/context/op_execution_context.py", line 296, in partition_key
    return self._step_execution_context.partition_key
  File "/home/urban/anaconda3/envs/myenv/lib/python3.8/site-packages/dagster/_core/execution/context/system.py", line 928, in partition_key
    raise DagsterInvariantViolationError(
[0m
